/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormInput: typeof import('./src/components/form/FormInput.vue')['default']
    GenericDataTable: typeof import('./src/components/GenericDataTable.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
}

// For TSX support
declare global {
  const AppHeader: typeof import('./src/components/AppHeader.vue')['default']
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const Column: typeof import('primevue/column')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const Divider: typeof import('primevue/divider')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const Form: typeof import('@primevue/forms/form')['default']
  const FormInput: typeof import('./src/components/form/FormInput.vue')['default']
  const GenericDataTable: typeof import('./src/components/GenericDataTable.vue')['default']
  const IconField: typeof import('primevue/iconfield')['default']
  const InputIcon: typeof import('primevue/inputicon')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const ProgressSpinner: typeof import('primevue/progressspinner')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Toast: typeof import('primevue/toast')['default']
}